### ISSUE TITLE
[BUG] mode for ansible.builtin.get_url causes error

### ISSUE THREAD

**Issue by tigitlabs** [TechDufus/dotfiles#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Thank you for sharing this repo,
In this file:
https://github.com/TechDufus/dotfiles/blob/main/roles/bash/tasks/ubuntu.yml

I had to change all the 'mode' flags to the "0755" syntax instead of 755.
I got permission problems when running the main.yml playbook

Update:
In line 21 same file:
`/{{ ansible_user_dir }}/oh-my-bash.install.sh`
This causing ansible trying to access a file in //$HOME
Changing it to:
"{{ ansible_user_dir }}/oh-my-bash.install.sh"

Fixes the problem 

### Steps To Reproduce

https://github.com/TechDufus/dotfiles/blob/main/roles/bash/tasks/ubuntu.yml

### Environment

- OS: Ubuntu 22.04
- Architecture: x86

### Anything else?
Happy to create a PR if you prefer that
_No response_

**Comment by TechDufus** [comment]
Can you provide the specific errors / logs that you're getting for this?

**Comment by tigitlabs** [comment]
Thank you checking now, in the meantime I am going to open another ticket, related with the `beautiful_output` plugin

**Comment by tigitlabs** [comment]
Thank you works ✅
Regarding the issue with `ansible.builtin.get_url` setting mode.
When running the playbook I get this error:

`Message: Destination /home/vscode/oh-my-bash.install.sh is not readable`

When checking permissions, you can see that the permissions are not set to `755` as intended.

``` bash
vscode ➜ ~ $ ls -la oh-my-bash.install.sh
--wxrw--wt 1 vscode vscode 11169 Feb 13 17:44 oh-my-bash.install.sh

vscode ➜ ~ $ sudo chmod 755 oh-my-bash.install.sh
vscode ➜ ~ $ ls -la oh-my-bash.install.sh
-rwxr-xr-x 1 vscode vscode 11169 Feb 13 17:44 oh-my-bash.install.sh

```

I am sorry for the messy Issue, I mixed up two things when I created it.
Do you prefer a new Issue for this topic?
Or a PR?

**Comment by TechDufus** [comment]
So wait. When you change all modes to "0755", this then works for you?

**Comment by tigitlabs** [comment]
Yes correct, I changed the mode in the bash/tasks to the quoted version and it started working.
But now setting up a test environment in codespaces the problem disappeared again.
But as you can see on the file permissions the initial playbook didn't run because of the mode being  set wrong.
This was on a local Ubuntu machine.

Probably still preferable using the quoted version as this is the only way that is documented in the `ansible.builtin.get_url` module

**Comment by TechDufus** [comment]
Nono You're right, This should be quoted. Thanks for catching these!
